#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define DISPLAY_PIN_ENABLE 12
#define DISPLAY_PIN_STROBE 13
#define DISPLAY_PIN_CLOCK 14
#define DISPLAY_PIN_DATA 25
#define DISPLAY_PIN_LED 26

#endif